---
version: 2

updates:
  - package-ecosystem: docker
    commit-message:
      prefix: "[docker] "
    directory: /
    schedule:
      interval: weekly
  - package-ecosystem: github-actions
    commit-message:
      prefix: "[github-actions] "
    directory: /
    schedule:
      interval: weekly
