---
name: CI

on:
  pull_request:
    types:
      - opened
      - ready_for_review
      - reopened
      - synchronize
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  ci:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ["3.8", "3.9", "3.10", "3.11"]
    runs-on: ${{ matrix.os }}
    if: ${{ !github.event.pull_request.draft }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Setup python
        uses: actions/setup-python@v4
        with:
          cache: pip
          python-version: ${{ matrix.python-version }}
      - uses: actions/cache@v3
        with:
          path: ${{ env.pythonLocation }}
          key: >
            ${{ runner.os }}
            -${{ matrix.python-version }}
            -${{ hashFiles('pyproject.toml') }}
      - name: Installing dependencies
        run: |
          pip install --upgrade-strategy eager -r requirements.txt
          pip install --upgrade-strategy eager -r requirements-dev.txt
      - name: Format
        run: |
          black --check .
          isort --check-only .
          docformatter -r .
      - name: Lint
        run: |
          yamllint .
          pydocstyle .
          flake8 .
          bandit -c=.bandit.yml -r src
          pylint src
          mypy .
      - name: Test
        run: pytest
